### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by milahu** [futurGH/ts-to-jsdoc#10]
ts-to-jsdoc is painfully slow

running the 2 small tests from #6 takes 40 seconds on my quad-core laptop

im aware that this is a limitation of the upstream [ts-morph](https://github.com/dsherret/ts-morph) which uses typescript under the hood

maybe we can disable type checking?
maybe we can use [swc](https://github.com/swc-project/swc)?

**Comment by futurGH** [comment]
Hm, a `ts-to-jsdoc` with `ts-morph` ripped out wouldn't really be `ts-to-jsdoc`.. I want to avoid scope creep without a compelling reason, since this isn't all that complex a project in the first place. If you want to try implementing that, go for it; I'd be happy to include a link in the README pointing to it as a faster option, but I don't think it's something I want to include in this project.

**Comment by milahu** [comment]
yeah, demand is like zero.
most people will just use [deno](https://github.com/denoland/deno) (based on `swc`) to run typescript
